### ISSUE TITLE
Menu types not working

### ISSUE THREAD

**Issue by Catalinn0** [Artillex-Studios/AxRewards#3]
When changing the menu type to anything other than chest I get this error:

```
[17:11:05 WARN]: java.lang.IllegalArgumentException: Size for custom inventory must be a multiple of 9 between 9 and 54 slots (got 5)
[17:11:05 WARN]: 	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:191)
[17:11:05 WARN]: 	at org.bukkit.craftbukkit.CraftServer.createInventory(CraftServer.java:2422)
[17:11:05 WARN]: 	at org.bukkit.Bukkit.createInventory(Bukkit.java:1908)
[17:11:05 WARN]: 	at AxRewards-2.0.1.jar//com.artillexstudios.axrewards.libs.gui.guis.BaseGui.updateTitle(BaseGui.java:501)
[17:11:05 WARN]: 	at AxRewards-2.0.1.jar//com.artillexstudios.axrewards.guis.impl.RewardGui.<init>(RewardGui.java:45)
[17:11:05 WARN]: 	at AxRewards-2.0.1.jar//com.artillexstudios.axrewards.guis.impl.GuiManager.openMenu(GuiManager.java:48)
[17:11:05 WARN]: 	at AxRewards-2.0.1.jar//com.artillexstudios.axrewards.commands.subcommands.Open.execute(Open.java:16)
[17:11:05 WARN]: 	at AxRewards-2.0.1.jar//com.artillexstudios.axrewards.commands.OpenCommand.open(OpenCommand.java:18)
```

I tried changing the rows value to anything from 1 to 6 and reloading the plugin each time but no matter what when using the /rewards command I get the error above in console and in game it says that the command or subcommand is invalid.

The server is running on paper-1.21-66 and the version of the plugin is AxRewards-2.0.1

**Comment by BenceX100** [comment]
Seems like an issue originating from the inventory library that we use, I will try to figure it out.
